import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar/Navbar"
// import Providers from "./Providers"
import Footer from "./component/Navbar/Footer.jsx"
import { Providers } from "./Redux/Provide.js";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
{/* <script src="https://checkout.razorpay.com/v1/checkout.js"></script> */}
      <body className={inter.className}>
        <Providers>
        <Navbar />
        {children}
        <Footer/>
        <ToastContainer />
        </Providers>
        </body>
    </html>
  );
}
