name: Build and Deploy Next.js Application

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your required Node.js version

      - name: Determine package manager
        id: detect-manager
        run: |
          cd disenosys/disenosys
          if [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            echo "command=install" >> $GITHUB_ENV
            echo "runner=yarn" >> $GITHUB_ENV
            exit 0
          elif [ -f "package.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            echo "command=ci" >> $GITHUB_ENV
            echo "runner=npx --no-install" >> $GITHUB_ENV
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi
        shell: bash

      - name: Install dependencies
        run: |
          cd disenosys/disenosys
          ${{ env.runner }} ${{ env.command }}

      - name: Build Next.js project
        run: |
          cd disenosys/disenosys
          ${{ env.runner }} build

      - name: Deploy
        run: |
          cd disenosys/disenosys
          ${{ env.runner }} deploy
